plugins {
    id 'java'
}

group = 'br.com.encibra'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation 'org.jetbrains:annotations:24.1.0'

    implementation 'org.springframework:spring-web:6.2.6'

    implementation 'io.swagger.core.v3:swagger-annotations:2.2.30'

    // JAKARTA
    implementation 'jakarta.persistence:jakarta.persistence-api:3.1.0'

    // JPA
    implementation 'org.springframework.data:spring-data-jpa:4.0.0-M2'

    // HIBERNATE
    implementation 'org.hibernate.orm:hibernate-core:6.6.14.Final'

    // JACKSON
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.19.0'

    // LOMBOK
    compileOnly("org.projectlombok:lombok:1.18.38")
    annotationProcessor("org.projectlombok:lombok:1.18.38")

    testCompileOnly("org.projectlombok:lombok:1.18.38")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.38")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

test {
    useJUnitPlatform()
}